//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitar
    {
        public int Id { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public System.DateTime AddDate { get; set; }
        public int ConditionId { get; set; }
        public int GuitarTypeId { get; set; }
        public string ImageURL { get; set; }
        public bool RotateImage { get; set; }
        public int Price { get; set; }
        public bool Sold { get; set; }
        public int SellerId { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual GuitarType GuitarType { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
